# Total Population Change
- https://censo.estadisticas.pr/EstimadosPoblacionales

In [110]:
import numpy as np
import pandas as pd

In [111]:
# Import the pop change factors Excel and clean useless formatting rows.
pob_total_df = pd.read_excel("../../data/raw/po-pr-change-factors.xlsx", sheet_name="Pob. Total", skiprows=[0, 1, 2])
pob_total_df = pob_total_df[:-5]
pob_total_df = pob_total_df.drop(56)
pob_total_df

               Unnamed: 0   Unnamed: 1         2020         2021         2022
0           United States  331449520.0  331511512.0  332031554.0  333287557.0
1               Northeast   57609156.0   57448898.0   57259257.0   57040406.0
2                 Midwest   68985537.0   68961043.0   68836505.0   68787595.0
3                   South  126266262.0  126450613.0  127346029.0  128716192.0
4                    West   78588565.0   78650958.0   78589763.0   78743364.0
5                .Alabama    5024356.0    5031362.0    5049846.0    5074296.0
6                 .Alaska     733378.0     732923.0     734182.0     733583.0
7                .Arizona    7151507.0    7179943.0    7264877.0    7359197.0
8               .Arkansas    3011555.0    3014195.0    3028122.0    3045637.0
9             .California   39538245.0   39501653.0   39142991.0   39029342.0
10              .Colorado    5773733.0    5784865.0    5811297.0    5839926.0
11           .Connecticut    3605942.0    3597362.0    3623355.0    3626205.0
12              .Delaware     989957.0     992114.0    1004807.0    1018396.0
13  .District of Columbia     689546.0     670868.0     668791.0     671803.0
14               .Florida   21538226.0   21589602.0   21828069.0   22244823.0
15               .Georgia   10711937.0   10729828.0   10788029.0   10912876.0
16                .Hawaii    1455273.0    1451043.0    1447154.0    1440196.0
17                 .Idaho    1839092.0    1849202.0    1904314.0    1939033.0
18              .Illinois   12812545.0   12786580.0   12686469.0   12582032.0
19               .Indiana    6785668.0    6788799.0    6813532.0    6833037.0
20                  .Iowa    3190372.0    3190571.0    3197689.0    3200517.0
21                .Kansas    2937847.0    2937919.0    2937922.0    2937150.0
22              .Kentucky    4505893.0    4507445.0    4506589.0    4512310.0
23             .Louisiana    4657749.0    4651664.0    4627098.0    4590241.0
24                 .Maine    1362341.0    1363557.0    1377238.0    1385340.0
25              .Maryland    6177213.0    6173205.0    6174610.0    6164660.0
26         .Massachusetts    7029949.0    6995729.0    6989690.0    6981974.0
27              .Michigan   10077325.0   10069577.0   10037504.0   10034113.0
28             .Minnesota    5706504.0    5709852.0    5711471.0    5717184.0
29           .Mississippi    2961288.0    2958141.0    2949586.0    2940057.0
30              .Missouri    6154920.0    6153998.0    6169823.0    6177957.0
31               .Montana    1084197.0    1087075.0    1106227.0    1122867.0
32              .Nebraska    1961489.0    1962642.0    1963554.0    1967923.0
33                .Nevada    3104624.0    3115648.0    3146402.0    3177772.0
34         .New Hampshire    1377518.0    1378587.0    1387505.0    1395231.0
35            .New Jersey    9289031.0    9271689.0    9267961.0    9261699.0
36            .New Mexico    2117527.0    2118390.0    2116677.0    2113344.0
37              .New York   20201230.0   20108296.0   19857492.0   19677151.0
38        .North Carolina   10439414.0   10449445.0   10565885.0   10698973.0
39          .North Dakota     779091.0     779518.0     777934.0     779261.0
40                  .Ohio   11799374.0   11797517.0   11764342.0   11756058.0
41              .Oklahoma    3959346.0    3964912.0    3991225.0    4019800.0
42                .Oregon    4237291.0    4244795.0    4256301.0    4240137.0
43          .Pennsylvania   13002689.0   12994440.0   13012059.0   12972008.0
44          .Rhode Island    1097371.0    1096345.0    1096985.0    1093734.0
45        .South Carolina    5118429.0    5131848.0    5193266.0    5282634.0
46          .South Dakota     886677.0     887799.0     896164.0     909824.0
47             .Tennessee    6910786.0    6925619.0    6968351.0    7051339.0
48                 .Texas   29145428.0   29232474.0   29558864.0   30029572.0
49                  .Utah    3271614.0    3283785.0    3339113.0    3380800.0
50               .Vermont     643085.0     642893.0     646972.0     647064.0
51              .Virginia    8631384.0    8636471.0    8657365.0    8683619.0
52            .Washington    7705247.0    7724031.0    7740745.0    7785786.0
53         .West Virginia    1793755.0    1791420.0    1785526.0    1775156.0
54             .Wisconsin    5893725.0    5896271.0    5880101.0    5892539.0
55               .Wyoming     576837.0     577605.0     579483.0     581381.0
57            Puerto Rico    3285874.0    3281557.0    3262693.0    3221789.0

In [112]:
# Drop all rows in pob_total_df except row 57 (Puerto Rico).
pob_total_df = pob_total_df.drop(pob_total_df.index[0:56]) if len(pob_total_df.index) > 1 else pob_total_df
pob_total_df

     Unnamed: 0  Unnamed: 1       2020       2021       2022
57  Puerto Rico   3285874.0  3281557.0  3262693.0  3221789.0

In [113]:
# Clean up column names.
pob_total_df.columns = ["State", "2021", "2020", "2021", "2022"]
pob_total_df.reset_index(drop=True, inplace=True)
pob_total_df

         State       2021       2020       2021       2022
0  Puerto Rico  3285874.0  3281557.0  3262693.0  3221789.0

# Population Change Factors

In [114]:
# Import the pop change factors Excel and clean useless formatting rows.
pob_change_factors = pd.read_excel("../../data/raw/po-pr-change-factors.xlsx", sheet_name="Componentes de cambio", skiprows=4)
pob_change_factors = pob_change_factors[:-8]
pob_change_factors

,Unnamed: 0,Unnamed: 1,Natural\nChange,Births,Deaths,Total,International2,Domestic,Unnamed: 8,Natural\nChange.1,Births.1,Deaths.1,Total.1,International2.1,Domestic.1
0,United States,1256003.0,245080.0,3688179.0,3443099.0,1010923.0,1010923.0,(X),1838037.0,431192.0,8164738.0,7733546.0,1406845.0,1406845.0,(X)
1,Northeast,-218851.0,29215.0,593222.0,564007.0,-246272.0,214464.0,-460736,-568750.0,-5705.0,1312124.0,1317829.0,-553194.0,299344.0,-852538
2,Midwest,-48910.0,-8638.0,759934.0,768572.0,-28781.0,145268.0,-174049,-197942.0,-19096.0,1697765.0,1716861.0,-192192.0,203644.0,-395836
3,South,1370163.0,70098.0,1476296.0,1406198.0,1282675.0,414740.0,867935,2449930.0,125506.0,3250442.0,3124936.0,2316894.0,578919.0,1737975
4,West,153601.0,154405.0,858727.0,704322.0,3301.0,236451.0,-233150,154799.0,330487.0,1904407.0,1573920.0,-164663.0,324938.0,-489601
5,.Alabama,24450.0,-8590.0,58280.0,66870.0,33206.0,4597.0,28609,49940.0,-21832.0,129259.0,151091.0,71884.0,6529.0,65355
6,.Alaska,-599.0,3092.0,9488.0,6396.0,-3755.0,2371.0,-6126,205.0,8432.0,21355.0,12923.0,-8106.0,3306.0,-11412
7,.Arizona,94320.0,-566.0,78763.0,79329.0,93203.0,22219.0,70984,207690.0,-5532.0,172257.0,177789.0,212851.0,30489.0,182362
8,.Arkansas,17515.0,-3936.0,36251.0,40187.0,21523.0,3314.0,18209,34082.0,-8980.0,79874.0,88854.0,42809.0,4754.0,38055
9,.California,-113649.0,106155.0,424652.0,318497.0,-217515.0,125715.0,-343230,-508903.0,201459.0,939969.0,738510.0,-699904.0,171223.0,-871127
10,.Colorado,28629.0,13705.0,63086.0,49381.0,15742.0,10366.0,5376,66193.0,32810.0,140739.0,107929.0,32506.0,14522.0,17984
11,.Connecticut,2850.0,916.0,35818.0,34902.0,2749.0,16296.0,-13547,20263.0,-3287.0,78179.0,81466.0,22847.0,22923.0,-76
12,.Delaware,13589.0,-718.0,10744.0,11462.0,14277.0,2451.0,11826,28439.0,-2099.0,23543.0,25642.0,30573.0,3454.0,27119
13,.District of Columbia,3012.0,2540.0,8096.0,5556.0,911.0,4558.0,-3647,-17743.0,5194.0,18587.0,13393.0,-19856.0,6354.0,-26210
14,.Florida,416754.0,-40216.0,220578.0,260794.0,444484.0,125629.0,318855,706597.0,-89047.0,478834.0,567881.0,797809.0,175333.0,622476
15,.Georgia,124847.0,16181.0,125538.0,109357.0,108691.0,27285.0,81406,200939.0,33065.0,276771.0,243706.0,166266.0,38177.0,128089
16,.Hawaii,-6958.0,2460.0,15788.0,13328.0,-9427.0,5785.0,-15212,-15077.0,6842.0,35141.0,28299.0,-21731.0,7953.0,-29684
17,.Idaho,34719.0,3686.0,22524.0,18838.0,30483.0,1844.0,28639,99941.0,10313.0,49863.0,39550.0,91246.0,2599.0,88647
18,.Illinois,-104437.0,4866.0,131491.0,126625.0,-110127.0,31529.0,-141656,-230513.0,6349.0,296603.0,290254.0,-238576.0,43472.0,-282048
19,.Indiana,19505.0,1024.0,80214.0,79190.0,20720.0,15490.0,5230,47369.0,1251.0,177200.0,175949.0,44591.0,21897.0,22694
20,.Iowa,2828.0,1559.0,36928.0,35369.0,2056.0,9348.0,-7292,10145.0,3049.0,82052.0,79003.0,6371.0,13248.0,-6877
21,.Kansas,-772.0,2008.0,34968.0,32960.0,-1925.0,5484.0,-7409,-697.0,5063.0,77759.0,72696.0,-6711.0,7681.0,-14392
22,.Kentucky,5721.0,-8358.0,52496.0,60854.0,14875.0,4455.0,10420,6417.0,-15426.0,116529.0,131955.0,20430.0,6328.0,14102
23,.Louisiana,-36857.0,1157.0,57152.0,55995.0,-38566.0,8106.0,-46672,-67508.0,414.0,127830.0,127416.0,-68797.0,11481.0,-80278
24,.Maine,8102.0,-5943.0,12030.0,17973.0,14125.0,2525.0,11600,22999.0,-11179.0,26607.0,37786.0,34237.0,3595.0,30642
25,.Maryland,-9950.0,11563.0,69130.0,57567.0,-21345.0,23756.0,-45101,-12553.0,20341.0,153727.0,133386.0,-34987.0,33300.0,-68287
26,.Massachusetts,-7716.0,6303.0,70019.0,63716.0,-13412.0,43880.0,-57292,-47975.0,6157.0,153672.0,147515.0,-49603.0,61263.0,-110866
27,.Michigan,-3391.0,-12482.0,105157.0,117639.0,10330.0,18812.0,-8482,-43212.0,-29226.0,234482.0,263708.0,-16923.0,26265.0,-43188
28,.Minnesota,5713.0,11617.0,64821.0,53204.0,-5206.0,14194.0,-19400,10680.0,26917.0,144350.0,117433.0,-17365.0,20012.0,-37377
29,.Mississippi,-9529.0,-4954.0,35060.0,40014.0,-4123.0,1593.0,-5716,-21231.0,-12601.0,78535.0,91136.0,-9125.0,2283.0,-11408
30,.Missouri,8134.0,-5994.0,69255.0,75249.0,15082.0,10058.0,5024,23037.0,-12195.0,155271.0,167466.0,34423.0,14190.0,20233
31,.Montana,16640.0,-1686.0,11173.0,12859.0,17804.0,1801.0,16003,38670.0,-2710.0,24791.0,27501.0,41598.0,2557.0,39041
32,.Nebraska,4369.0,5105.0,24376.0,19271.0,-252.0,4018.0,-4270,6434.0,11404.0,54682.0,43278.0,-5414.0,5694.0,-11108
33,.Nevada,31370.0,392.0,33784.0,33392.0,30944.0,10163.0,20781,73148.0,2403.0,75239.0,72836.0,70228.0,13911.0,56317
34,.New Hampshire,7726.0,-2030.0,12670.0,14700.0,10203.0,3900.0,6303,17713.0,-4099.0,27771.0,31870.0,21568.0,5530.0,16038
35,.New Jersey,-6262.0,19751.0,102555.0,82804.0,-24843.0,39388.0,-64231,-27332.0,24198.0,225069.0,200871.0,-52712.0,55037.0,-107749
36,.New Mexico,-3333.0,-4295.0,20955.0,25250.0,1389.0,5893.0,-4504,-4183.0,-7845.0,47605.0,55450.0,3253.0,8311.0,-5058
37,.New York,-180341.0,35611.0,212145.0,176534.0,-221634.0,77923.0,-299557,-524079.0,44830.0,471030.0,426200.0,-556885.0,108036.0,-664921
38,.North Carolina,133088.0,6459.0,122179.0,115720.0,126226.0,26430.0,99796,259559.0,10940.0,267681.0,256741.0,248898.0,37031.0,211867
39,.North Dakota,1327.0,2799.0,10164.0,7365.0,-1442.0,1268.0,-2710,170.0,5846.0,22785.0,16939.0,-5434.0,1752.0,-7186
40,.Ohio,-8284.0,-19543.0,129529.0,149072.0,14947.0,24112.0,-9165,-43316.0,-39559.0,290090.0,329649.0,-6004.0,33911.0,-39915
41,.Oklahoma,28575.0,-3283.0,48107.0,51390.0,32528.0,5737.0,26791,60454.0,-5435.0,107055.0,112490.0,64907.0,8100.0,56807
42,.Oregon,-16164.0,-5089.0,41143.0,46232.0,-10305.0,7026.0,-17331,2846.0,-6562.0,91159.0,97721.0,9036.0,9812.0,-776
43,.Pennsylvania,-40051.0,-23021.0,132099.0,155120.0,-13216.0,26741.0,-39957,-30681.0,-56154.0,294979.0,351133.0,21346.0,37564.0,-16218
44,.Rhode Island,-3251.0,-566.0,10544.0,11110.0,-2397.0,2799.0,-5196,-3637.0,-2743.0,23103.0,25846.0,-1333.0,3948.0,-5281
45,.South Carolina,89368.0,-7460.0,57071.0,64531.0,94684.0,10654.0,84030,164205.0,-17582.0,126154.0,143736.0,180965.0,15017.0,165948
46,.South Dakota,13660.0,2161.0,11392.0,9231.0,11205.0,2781.0,8424,23147.0,4170.0,25291.0,21121.0,18655.0,3944.0,14711
47,.Tennessee,82988.0,-9213.0,81970.0,91183.0,89742.0,8096.0,81646,140553.0,-18994.0,180491.0,199485.0,157821.0,11418.0,146403
48,.Texas,470708.0,118159.0,379412.0,261253.0,349575.0,118614.0,230961,884144.0,243520.0,831637.0,588117.0,639314.0,164062.0,475252
49,.Utah,41687.0,23549.0,46912.0,23363.0,18312.0,5414.0,12898,109186.0,54182.0,104519.0,50337.0,54712.0,7587.0,47125
50,.Vermont,92.0,-1806.0,5342.0,7148.0,2153.0,1012.0,1141,3979.0,-3428.0,11714.0,15142.0,7341.0,1448.0,5893
51,.Virginia,26254.0,12925.0,96748.0,83823.0,13740.0,37692.0,-23952,52235.0,27930.0,214851.0,186921.0,22987.0,52762.0,-29775
52,.Washington,45041.0,13492.0,84270.0,70778.0,33932.0,37512.0,-3580,80539.0,36938.0,187840.0,150902.0,44796.0,52172.0,-7376
53,.West Virginia,-10370.0,-12158.0,17484.0,29642.0,2247.0,1773.0,474,-18599.0,-23902.0,39084.0,62986.0,4996.0,2536.0,2460
54,.Wisconsin,12438.0,-1758.0,61639.0,63397.0,15831.0,8174.0,7657,-1186.0,-2165.0,137200.0,139365.0,195.0,11578.0,-11383
55,.Wyoming,1898.0,-490.0,6189.0,6679.0,2494.0,342.0,2152,4544.0,-243.0,13930.0,14173.0,4852.0,496.0,4356
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Puerto Rico,-40904.0,-14457.0,19645.0,34102.0,-26447.0,-26447.0,(X),-64085.0,-31760.0,42984.0,74744.0,-32325.0,-32325.0,(X)

In [115]:
# Drop all rows in pob_total_df except row 57 (Puerto Rico).
pob_change_factors = pob_change_factors.drop(pob_change_factors.index[0:57]) if len(pob_change_factors.index) > 1 else pob_change_factors
pob_total_df.reset_index(drop=True, inplace=True)
pob_change_factors

,Unnamed: 0,Unnamed: 1,Natural\nChange,Births,Deaths,Total,International2,Domestic,Unnamed: 8,Natural\nChange.1,Births.1,Deaths.1,Total.1,International2.1,Domestic.1
57,Puerto Rico,-40904.0,-14457.0,19645.0,34102.0,-26447.0,-26447.0,(X),-64085.0,-31760.0,42984.0,74744.0,-32325.0,-32325.0,(X)

In [116]:
# Turn this into a MultiIndex DataFrame.
level1 = ['Annual Change', 'Cumulative Change']
level2 = ['Total Change', 'Natural Change', 'Births', 'Deaths', 'Net Migration (Total)', 'Net Migration (International)', 'Net Migration (Domestic)']
labels = [(l1, l2) for l1 in level1 for l2 in level2]
columns = pd.MultiIndex.from_tuples(labels)
pob_change_factors.columns = columns.insert(0, 'State')
pob_change_factors.reset_index(drop=True, inplace=True)
pob_change_factors

         State Annual Change
                Total Change Natural Change   Births   Deaths
0  Puerto Rico      -40904.0       -14457.0  19645.0  34102.0  \


  Net Migration (Total) Net Migration (International)
0              -26447.0                      -26447.0  \

                           Cumulative Change
  Net Migration (Domestic)      Total Change Natural Change   Births   Deaths
0                      (X)          -64085.0       -31760.0  42984.0  74744.0  \


  Net Migration (Total) Net Migration (International) Net Migration (Domestic)
0              -32325.0                      -32325.0                      (X)

In [117]:
# Puerto Rico doesn't have domestic migration, so we'll drop that column.
pob_change_factors = pob_change_factors.drop(columns=[('Annual Change', 'Net Migration (Domestic)'), ('Cumulative Change', 'Net Migration (Domestic)')])
pob_change_factors

         State Annual Change
                Total Change Natural Change   Births   Deaths
0  Puerto Rico      -40904.0       -14457.0  19645.0  34102.0  \

                                                      Cumulative Change
  Net Migration (Total) Net Migration (International)      Total Change
0              -26447.0                      -26447.0          -64085.0  \


  Natural Change   Births   Deaths Net Migration (Total)
0       -31760.0  42984.0  74744.0              -32325.0  \


  Net Migration (International)
0                      -32325.0

# Final Results
Two datasets are extracted from multiple Excel sheets.

In [119]:
# Output the DataFrame to CSV, and overwrite if the file already exists.
pob_total_df.to_csv("../../data/clean/po-pr-total-change-clean.csv", index=False)
pob_change_factors.to_csv("../../data/clean/po-pr-change-factors-clean.csv", index=False)